version: '3.7'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx-test
    ports:
      - 8081:80
  nginx:
    image: nginx:alpine
    container_name: nginx-2
    ports:
      - 8082:80
